### ISSUE TITLE
Flutter Pub Get Command Fails

### ISSUE THREAD

**Issue by tataDan** [icedman/flutter_editor#1]
When I run `flutter pub get` I get the following message:

`daniel@dellOptiplex9020:~/flutterProjects/flutter_editor_main$ flutter pub get
Git error. Command: `git clone --mirror git://github.com/icedman/highlight.dart /home/daniel/.pub-cache/git/cache/highlight.dart-80302663b9f4ae01119320ffc91eea2730fea27a`
stdout: 
stderr: Cloning into bare repository '/home/daniel/.pub-cache/git/cache/highlight.dart-80302663b9f4ae01119320ffc91eea2730fea27a'...
fatal: remote error: 
  The unauthenticated git protocol on port 9418 is no longer supported.
Please see https://github.blog/2021-09-01-improving-git-protocol-security-github/ for more information.
exit code: 128
pub get failed (server unavailable) -- attempting retry 1 in 1 second...
`

**Comment by tataDan** [comment]
If I run `git config --global url."https://".insteadOf git://` before running `flutter pub get`, then I do not get the error.  However, I do not know whether or not this command might have any negative unintended consequences.

**Comment by icedman** [comment]
Please edit the override and try:
http://github.com/icedman/highlight.dart 
'http:' instead of 'git:'
or 
Try removing the override - line-by-line parsing wouldn't work well in this case
