### ISSUE TITLE
“onigmognu.h”: No such file or directory

### ISSUE THREAD

**Issue by jonahzheng** [icedman/flutter_editor#4]
build in windows.
flutter_editor\libs\tm-parser\textmate\parser\pattern.h(9,10): fatal error C1083:   “onigmognu.h”: No such file or directory [flutter_editor\build\windows\runner\editor_api.vcxproj]
flutter_editor\libs\tm-parser\textmate\parser\pattern.h(9,10): fatal error C1083:  : “onigmognu.h”: No such file or directory

**Comment by icedman** [comment]
add onigmu under libs, configure and build
https://github.com/k-takata/Onigmo

add jsoncpp and run amalgamate.py

**Comment by jonahzheng** [comment]
@icedman thank you.
